### PR TITLE
[BACKLOG-12703] Mavenize pentaho-data-mining-ee

### PR DESCRIPTION
**Pull request by jgminder**
@pentaho/2-1b please review.

### CODE REVIEW

**Comment by hbfernandes** [comment]
pdi-wekascoring-plugin-package-8.0-SNAPSHOT.zip is missing weka-scoring/lib/xpp3_min-1.1.3.4.O.jar, is that intentional?
Maven isn't generating a dm-commons-package-8.0-SNAPSHOT.zip that was previously created, did you notice that also?
I would take the package suffix from pdi-wekascoring-plugin-package-8.0-SNAPSHOT.zip, just to make it consistent. 
Additionally, be carefull with your assemblies and dependency sets. By default useTransitiveDependencies is true, and that might cause weird stuff at some point. Having copy-dependencies on the pom and filesets on the assembly is always safer.

**Comment by jgminder** [comment]
@hbfernandes I left weka-scoring/lib/xpp3_min-1.1.3.4.O.jar out on purpose. I ran mvn dependency:analyze and it wasn't necessary. 

As for dm-commons-package-8.0-SNAPSHOT.zip, nothing seemed to use it, only the jar so I just didn't bother creating it since it wasn't consumed anywhere.

I'll update the pdi-wekascoring-plugin-package-8.0-SNAPSHOT.zip to remove the package suffix. I can update the PR to using copy dependencies and filesets as well.

**Comment by hbfernandes** [comment]
@jgminder I'd change the dependencySets honestly, made it as a rule to not use them if using the transitives. If anywhere in the transitives there are "*" exclusions it will ignore and bring everything and we already had issues with that, so I'd rather be safe.

**Comment by jgminder** [comment]
@pentaho/2-1b Closing this PR as it was submitted under the wrong ticket number and branch name. Changing the branch name will close the PR anyway so I'll just close it and resubmit. It was supposed to correspond with BACKLOG-12687.

**Pull request closed without merging**
